# Generated by Django 3.2.4 on 2021-11-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptiveStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_trending', models.TextField(verbose_name='时间发帖趋势')),
                ('user_trending', models.TextField(verbose_name='用户发帖趋势')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task')),
            ],
            options={
                'verbose_name': '描述性统计',
                'verbose_name_plural': '描述性统计',
            },
        ),
    ]
