# Generated by Django 3.2.4 on 2021-11-12 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_column_is_text'),
        ('statistics_figure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptivestatistics',
            name='task',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.task'),
        ),
    ]
