# Generated by Django 3.2.4 on 2021-11-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_figure', '0003_auto_20211112_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptivestatistics',
            name='time_trending',
            field=models.FileField(upload_to='figure', verbose_name='时间发帖趋势'),
        ),
        migrations.AlterField(
            model_name='descriptivestatistics',
            name='user_trending',
            field=models.FileField(upload_to='figure', verbose_name='用户发帖趋势'),
        ),
    ]
