# Generated by Django 3.2.9 on 2021-11-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_column_is_text'),
        ('statistics_figure', '0004_auto_20211112_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptivestatistics',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task'),
        ),
        migrations.AlterField(
            model_name='descriptivestatistics',
            name='time_trending',
            field=models.FileField(blank=True, null=True, upload_to='figure', verbose_name='时间发帖趋势'),
        ),
        migrations.AlterField(
            model_name='descriptivestatistics',
            name='user_trending',
            field=models.FileField(blank=True, null=True, upload_to='figure', verbose_name='用户发帖趋势'),
        ),
    ]
