# Generated by Django 3.2.4 on 2021-11-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_step',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='posts',
            field=models.FileField(blank=True, null=True, upload_to='dataset'),
        ),
    ]
