# Generated by Django 3.2.4 on 2021-11-12 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_manager', '0002_auto_20211112_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='busy',
            field=models.BooleanField(default=False, verbose_name='繁忙'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='current_step',
            field=models.IntegerField(default=3, verbose_name='创建步骤'),
        ),
        migrations.AlterField(
            model_name='task',
            name='posts',
            field=models.FileField(blank=True, null=True, upload_to='dataset', verbose_name='帖子数据集'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_datetime', models.BooleanField(default=False, verbose_name='时间?')),
                ('is_user_id', models.BooleanField(default=False, verbose_name='用户编号?')),
                ('is_interaction', models.BooleanField(default=False, verbose_name='互动指标?')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '列',
                'verbose_name_plural': '列',
            },
        ),
    ]
