# Generated by Django 3.2.4 on 2021-11-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20211112_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='name',
            field=models.TextField(default='noname', verbose_name='名称'),
            preserve_default=False,
        ),
    ]
