# Generated by Django 3.2.4 on 2021-11-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': '注册', 'verbose_name_plural': '注册'},
        ),
        migrations.AlterModelOptions(
            name='registergroup',
            options={'verbose_name': '可注册的组', 'verbose_name_plural': '可注册的组'},
        ),
        migrations.AlterField(
            model_name='register',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='组'),
        ),
        migrations.AlterField(
            model_name='register',
            name='invitation_code',
            field=models.TextField(unique=True, verbose_name='邀请码'),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=150, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=150, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='registergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='组'),
        ),
    ]
