# Generated by Django 3.2.9 on 2021-11-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_time_series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decompositioncontent',
            name='pca_figure',
            field=models.FileField(blank=True, null=True, upload_to='figure', verbose_name='解释方差比率图'),
        ),
        migrations.AlterField(
            model_name='decompositioncontent',
            name='pca_x_lower_bound',
            field=models.IntegerField(default=768, verbose_name='主成分图横轴下边界'),
        ),
        migrations.AlterField(
            model_name='decompositioncontent',
            name='pca_x_upper_bound',
            field=models.IntegerField(default=0, verbose_name='主成分图横轴上边界'),
        ),
    ]
