# Generated by Django 3.2.9 on 2021-11-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_time_series', '0002_auto_20211114_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompositioncontent',
            name='pca_x_lower_bound',
        ),
        migrations.RemoveField(
            model_name='decompositioncontent',
            name='pca_x_upper_bound',
        ),
    ]
