# Generated by Django 3.2.9 on 2021-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_time_series', '0003_auto_20211114_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompositioncontent',
            name='clusters_detail',
            field=models.TextField(blank=True, verbose_name='类别详细'),
        ),
    ]
