# Generated by Django 3.2.9 on 2021-11-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granger_causality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grangercausality',
            name='direction_sender',
            field=models.BooleanField(default=True, verbose_name='因果方向(是否主动方?)'),
        ),
    ]
