# Generated by Django 3.2.9 on 2021-11-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granger_causality', '0002_grangercausality_direction_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grangercausality',
            old_name='direction_sender',
            new_name='direction',
        ),
        migrations.RemoveField(
            model_name='grangercausality',
            name='results',
        ),
    ]
