# Generated by Django 3.2.9 on 2021-11-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_manager', '0005_column_is_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BERT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_features', models.FileField(blank=True, null=True, upload_to='intermediate', verbose_name='文本特征')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task', verbose_name='任务')),
            ],
        ),
    ]
